//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCManager.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCManager.Data.BaseResources", typeof(BaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Hi, {{receiverEmail}}&lt;/h2&gt;
        ///&lt;p&gt;{{message}}&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;div&gt;
        ///&lt;p&gt;Best regards,&lt;/p&gt;
        ///&lt;div&gt;&lt;strong&gt;&lt;strong&gt;The SCManager team&amp;nbsp;&lt;/strong&gt;&lt;/strong&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;/div&gt;
        ///&lt;div&gt;Email: &lt;a href=&quot;mailto:scmanager_test@mail.com&quot;&gt;scmanager_test@mail.com&lt;/a&gt;&lt;/div&gt;
        ///&lt;div&gt;&amp;nbsp;&lt;/div&gt;
        ///&lt;div&gt;&lt;img src=&quot;https://res.cloudinary.com/dffy4iztl/image/upload/v1591208148/favicon_vfx2uo.ico&quot; alt=&quot;&quot; width=&quot;48&quot; height=&quot;48&quot; /&gt;&lt;/div [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailBaseContent {
            get {
                return ResourceManager.GetString("EmailBaseContent", resourceCulture);
            }
        }
    }
}
