//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCManager.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SeedingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeedingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCManager.Data.SeedingResources", typeof(SeedingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:&quot;37152c28-98e0-4067-93eb-f708a463d91b&quot;,&quot;Name&quot;:&quot;User&quot;,&quot;NormalizedName&quot;:&quot;USER&quot;,&quot;ConcurrencyStamp&quot;:&quot;514f4df7-f0a4-4b34-aaf8-54c4c874f824&quot;},{&quot;Id&quot;:&quot;c5fb4568-51c6-43ab-8050-a5642eb9ac44&quot;,&quot;Name&quot;:&quot;Administrator&quot;,&quot;NormalizedName&quot;:&quot;ADMINISTRATOR&quot;,&quot;ConcurrencyStamp&quot;:&quot;55309049-c467-42fd-9223-e221b7c3b61a&quot;}].
        /// </summary>
        internal static string AspNetRoles {
            get {
                return ResourceManager.GetString("AspNetRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;UserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;RoleId&quot;:&quot;c5fb4568-51c6-43ab-8050-a5642eb9ac44&quot;}].
        /// </summary>
        internal static string AspNetUserRoles {
            get {
                return ResourceManager.GetString("AspNetUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;UserName&quot;:&quot;scmanager_test@mail.com&quot;,&quot;NormalizedUserName&quot;:&quot;SCMANAGER_TEST@MAIL.COM&quot;,&quot;Email&quot;:&quot;scmanager_test@mail.com&quot;,&quot;NormalizedEmail&quot;:&quot;SCMANAGER_TEST@MAIL.COM&quot;,&quot;EmailConfirmed&quot;:true,&quot;PasswordHash&quot;:&quot;AQAAAAEAACcQAAAAEM9A4bvt\/Ci2fC2r5Si1p2dEX8\/v8\/svgQqI1rqocSOUcWqgfzD8A8OGlpU\/6qiZbQ==&quot;,&quot;SecurityStamp&quot;:&quot;UFEWI655NFJHSNPMEJBEGWHAJKHAVWIW&quot;,&quot;ConcurrencyStamp&quot;:&quot;53ea6bca-6c80-400c-9cb5-ac31d508a7f7&quot;,&quot;PhoneNumberConfirmed&quot;:false,&quot;TwoFactorEnabled&quot;:false,&quot;LockoutEnabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspNetUsers {
            get {
                return ResourceManager.GetString("AspNetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;CreatedDateTime&quot;:&quot;2020-06-19T19:07:40.9794689&quot;,&quot;IsActive&quot;:true,&quot;ComponentTypeId&quot;:11,&quot;Name&quot;:&quot;Input Voltage&quot;,&quot;Unit&quot;:&quot;Volt Amper&quot;,&quot;CreatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;Symbol&quot;:&quot;VAC&quot;,&quot;IsPrimary&quot;:true},{&quot;Id&quot;:2,&quot;CreatedDateTime&quot;:&quot;2020-06-19T19:08:01.0589372&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-06-19T19:08:10.3688734&quot;,&quot;IsActive&quot;:true,&quot;ComponentTypeId&quot;:11,&quot;Name&quot;:&quot;Output Voltage&quot;,&quot;Unit&quot;:&quot;Volt&quot;,&quot;CreatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;LastUpdatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComponentTypeDetails {
            get {
                return ResourceManager.GetString("ComponentTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;CreatedDateTime&quot;:&quot;2020-06-18T12:04:56.3178451&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-06-18T12:12:00.4710893&quot;,&quot;IsActive&quot;:true,&quot;Name&quot;:&quot;DIAC&quot;,&quot;CreatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;LastUpdatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;ImageId&quot;:&quot;rvujbwa21jy4nqzpv6nh&quot;},{&quot;Id&quot;:2,&quot;CreatedDateTime&quot;:&quot;2020-06-18T12:19:20.8560471&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-06-18T12:24:20.9437730&quot;,&quot;IsActive&quot;:true,&quot;Name&quot;:&quot;Diode&quot;,&quot;CreatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;LastUpdatedByUserId&quot;:&quot;7b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComponentTypes {
            get {
                return ResourceManager.GetString("ComponentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:5,&quot;CreatedDateTime&quot;:&quot;2020-05-28T00:00:00&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-06-19T19:33:13.8923650&quot;,&quot;CreatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;LastUpdatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;IsActive&quot;:true,&quot;Name&quot;:&quot;About&quot;,&quot;Content&quot;:&quot;&lt;h3 style=\&quot;margin: 1em 0 1.5rem; padding: 0; font-size: 1.5rem; color: rgba(54, 54, 54, 1); line-height: 1.125; font-family: BlinkMacSystemFont, -apple-system, &apos;Segoe UI&apos;, Roboto, Oxygen, Ubuntu, Cantarell, &apos;Fira Sans&apos;, &apos;Droid Sans&apos;, &apos;Helvetica Neue&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StaticSiteInfos {
            get {
                return ResourceManager.GetString("StaticSiteInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;CreatedDateTime&quot;:&quot;2020-06-18T12:27:55.0671817&quot;,&quot;IsActive&quot;:true,&quot;Name&quot;:&quot; &quot;,&quot;CreatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;},{&quot;Id&quot;:2,&quot;CreatedDateTime&quot;:&quot;2020-06-18T12:43:59.2395842&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-06-18T12:57:50.2142519&quot;,&quot;IsActive&quot;:true,&quot;Name&quot;:&quot;G&quot;,&quot;CreatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;LastUpdatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;},{&quot;Id&quot;:3,&quot;CreatedDateTime&quot;:&quot;2020-06-18T12:45:38.7085628&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-06-18T12:57:57.0727780&quot;,&quot;IsActiv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnitMultipliers {
            get {
                return ResourceManager.GetString("UnitMultipliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;CreatedDateTime&quot;:&quot;2020-06-19T19:26:28.7966621&quot;,&quot;CreatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-06-19T19:29:04.0409235&quot;,&quot;LastUpdatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;IsActive&quot;:true,&quot;UserComponentTypeId&quot;:1,&quot;UnitMultiplierId&quot;:1,&quot;ComponentTypeDetailId&quot;:27,&quot;Value&quot;:10.00},{&quot;Id&quot;:2,&quot;CreatedDateTime&quot;:&quot;2020-06-19T19:26:28.8109060&quot;,&quot;CreatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-06-19T19:29:04.0409396&quot;,&quot;LastUpdatedByUse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserComponentTypeDetails {
            get {
                return ResourceManager.GetString("UserComponentTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;CreatedDateTime&quot;:&quot;2020-06-19T19:26:28.6186808&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-06-19T19:29:04.0404024&quot;,&quot;IsActive&quot;:true,&quot;ComponentTypeId&quot;:1,&quot;Quantity&quot;:10,&quot;UnitPrice&quot;:12.50,&quot;CreatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;,&quot;LastUpdatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e1-dc7f0381d7fa&quot;},{&quot;Id&quot;:2,&quot;CreatedDateTime&quot;:&quot;2020-06-19T19:27:24.1804903&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-06-19T19:27:36.1800413&quot;,&quot;IsActive&quot;:true,&quot;ComponentTypeId&quot;:5,&quot;Quantity&quot;:50,&quot;UnitPrice&quot;:1.30,&quot;CreatedByUserId&quot;:&quot;7b26038d-1a43-4248-90e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserComponentTypes {
            get {
                return ResourceManager.GetString("UserComponentTypes", resourceCulture);
            }
        }
    }
}
