//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCManager.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SeedingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeedingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCManager.Data.SeedingResources", typeof(SeedingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:&quot;3aab7018-2979-4572-b055-4669e941539e&quot;,&quot;UserName&quot;:&quot;scmanager_test@mail.com&quot;,&quot;NormalizedUserName&quot;:&quot;SCMANAGER_TEST@MAIL.COM&quot;,&quot;Email&quot;:&quot;scmanager_test@mail.com&quot;,&quot;NormalizedEmail&quot;:&quot;SCMANAGER_TEST@MAIL.COM&quot;,&quot;EmailConfirmed&quot;:true,&quot;PasswordHash&quot;:&quot;AQAAAAEAACcQAAAAENVTuxD0CHO58asb1YYHB7BCfrbb28i8QbuIWy0eGcGaqcAk7eZ7l2vhxxFAC588IQ==&quot;,&quot;SecurityStamp&quot;:&quot;ROXYKWZHZ7G3OCTW6353NH34QHXJ2JMF&quot;,&quot;ConcurrencyStamp&quot;:&quot;0362063e-dd67-4a62-8373-3571d9c57a8e&quot;,&quot;PhoneNumberConfirmed&quot;:false,&quot;TwoFactorEnabled&quot;:false,&quot;LockoutEnabled&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspNetUsers {
            get {
                return ResourceManager.GetString("AspNetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:5,&quot;CreatedDateTime&quot;:&quot;2020-05-28T00:00:00&quot;,&quot;CreatedByUserId&quot;:&quot;3aab7018-2979-4572-b055-4669e941539e&quot;,&quot;IsActive&quot;:true,&quot;Name&quot;:&quot;About&quot;,&quot;Content&quot;:&quot;&lt;h2&gt;About&lt;\/h2&gt;\r\n&lt;p&gt;SCManager is a semiconductors management application,&lt;\/p&gt;\r\n&lt;p&gt;which can also be used for a Bayesian analysis.&lt;\/p&gt;\r\n&lt;p&gt;&amp;nbsp;&lt;\/p&gt;\r\n&lt;h2&gt;Thank your for using our application!&lt;\/h2&gt;\r\n&lt;p&gt;This about info is effective as of 28 May 2020.&lt;\/p&gt;&quot;},{&quot;Id&quot;:6,&quot;CreatedDateTime&quot;:&quot;2020-05-28T00:00:00&quot;,&quot;CreatedByUserId&quot;:&quot;3aab7018-2979-4572-b055-466 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StaticSiteInfos {
            get {
                return ResourceManager.GetString("StaticSiteInfos", resourceCulture);
            }
        }
    }
}
